version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists..."
      - apt update -y
      - echo "Installing Nginx..."
      - apt install -y nginx

  build:
    commands:
      - echo "Starting build phase..."
      - mkdir -p /tmp/build-output
      - cp index.html /tmp/build-output/

  post_build:
    commands:
      - echo "Post-build phase completed."

artifacts:
  files:
    - index.html
  base-directory: /tmp/build-output
