version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists..."
      - sudo apt-get update
      - echo "Installing Nginx..."
      - sudo apt-get install nginx -y

  build:
    commands:
      - echo "Starting build phase..."
      - cp index.html /var/www/html/

  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - '**/*'
